version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    AWS_ACCOUNT_ID: 873976611862
    IMAGE_REPO_NAME: bia
    ECS_CLUSTER_NAME: cluster-bia-alb
    ECS_SERVICE_NAME: service-bia-alb
    ECS_TASK_DEFINITION: task-def-bia-alb
    ALB_URL: bia-alb-690586468.us-east-1.elb.amazonaws.com

phases:
  pre_build:
    commands:
      - echo "=== PRE-BUILD PHASE ==="
      - echo "Build iniciado em $(date)"
      - echo "Fazendo login no Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo "Repository URI: $REPOSITORY_URI"
      - echo "Commit Hash: $COMMIT_HASH"
      - echo "Image Tag: $IMAGE_TAG"
      
  build:
    commands:
      - echo "=== BUILD PHASE ==="
      - echo "Build da aplicação iniciado em $(date)"
      - echo "Construindo imagem Docker da aplicação BIA..."
      - echo "Configurando VITE_API_URL para ALB: http://$ALB_URL"
      - docker build --build-arg VITE_API_URL=http://$ALB_URL -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI:latest
      - echo "Build da imagem concluído com sucesso"
      
  post_build:
    commands:
      - echo "=== POST-BUILD PHASE ==="
      - echo "Build finalizado com sucesso em $(date)"
      - echo "Fazendo push da imagem para Amazon ECR..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Push concluído com sucesso"
      - echo "Gerando arquivo imagedefinitions.json para ECS..."
      - printf '[{"name":"bia","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo "Conteúdo do imagedefinitions.json:"
      - cat imagedefinitions.json
      - echo "Verificando se a imagem foi enviada corretamente..."
      - aws ecr describe-images --repository-name $IMAGE_REPO_NAME --image-ids imageTag=$IMAGE_TAG --region $AWS_DEFAULT_REGION
      - echo "=== BUILD PROCESS COMPLETED ==="

artifacts:
  files:
    - imagedefinitions.json
  name: bia-build-artifacts
